# config/packages/easy_admin.yaml
easy_admin:
  entities:
    form:
      fields:
        - { property: 'imageFile', type: 'vich_image' }
    design:
      form_theme:
        - '@EasyAdmin/form/bootstrap_4.html.twig'
        - '@VichUploader/Form/fields.html.twig'
    Product:
      # ...
      list:
        fields:
          - {
              property: 'image',
              type: 'image',
              base_path: '%app.path.product_images%',
            }
      # ...
      show:
        fields:
          - {
              property: 'image',
              type: 'image',
              base_path: '%app.path.product_images%',
            }
